CREATE TABLE IF NOT EXISTS DF_COUPON
(
    ID                BIGINT NOT NULL AUTO_INCREMENT,
    SERIAL            VARCHAR(64) NOT NULL,
    CODE              VARCHAR(64) NOT NULL,
    KIND              VARCHAR(32) NOT NULL,
    EXPIRATION        DATETIME NOT NULL,
    REGION            VARCHAR(32) NOT NULL,
    AMOUNT            DOUBLE(10,2) NOT NULL,
    CREATE_AT         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_AT         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    USE_TIME          DATETIME,
    USERNAME          VARCHAR(32),
    NAMESPACE         VARCHAR(64),
    STATUS            VARCHAR(32),
    PRIMARY KEY (ID)
) DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS DF_ITEM_STAT
(
   STAT_KEY     VARCHAR(255) NOT NULL COMMENT '3*255 = 765 < 767',
   STAT_VALUE   INT NOT NULL,
   PRIMARY KEY (STAT_KEY)
) DEFAULT CHARSET=UTF8;
